# Generated by Django 4.2.4 on 2024-08-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsection',
            old_name='markdown_content',
            new_name='html_content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='slug',
        ),
        migrations.AddField(
            model_name='section',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
