# Generated by Django 4.2.4 on 2024-08-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_rename_markdown_content_subsection_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='markdown_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='markdown_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
