# Generated by Django 4.2.4 on 2024-08-25 12:14

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_section_markdown_content_subsection_markdown_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='markdown_content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='markdown_content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
